=== SolaZhao/freescale/CWS12v5.2/Bin/Plugins/Support/HC12Wizard/wizard.dtd
<?xml version="1.0" encoding="UTF-8"?>
<?codewarrior wizardversion="1.0" ideversion="5.2" ?>
<!ELEMENT WIZARD (FEATURES?, WIZARDDIALOGCONFIGLIST?, DIALOGLIST?, WIZARDELEMENTLIST?, TEMPLATELIST?, REJECTIONLIST?)>
<!ATTLIST WIZARD
	name CDATA #IMPLIED
>
<!ELEMENT FEATURES (NEWPROJECTWIZARD?, AUTONEWPROJECTLIST?, PROJECTRECONFIGUREWIZARDLIST?, QUICKRECONFIGURELIST?, STARTUPDIALOG?, TOOLBARICONFILES?)>
<!ELEMENT NEWPROJECTWIZARDLIST (NEWPROJECTWIZARD+)>
<!ELEMENT NEWPROJECTWIZARD EMPTY>
<!ATTLIST NEWPROJECTWIZARD
	wizardID IDREF #REQUIRED
>
<!ELEMENT AUTONEWPROJECTLIST (AUTONEWPROJECT+)>
<!ELEMENT AUTONEWPROJECT (FILETYPELIST+)>
<!ATTLIST AUTONEWPROJECT
	wizardID IDREF #REQUIRED
>
<!ELEMENT FILETYPELIST (FILETYPE+)>
<!ELEMENT FILETYPE (WIZARDELEMENTREF*)>
<!ATTLIST FILETYPE
	extension CDATA #REQUIRED
>
<!ELEMENT PROJECTRECONFIGUREWIZARDLIST (PROJECTRECONFIGUREWIZARD+)>
<!ELEMENT PROJECTRECONFIGUREWIZARD (WIZARDELEMENTREF*)>
<!ATTLIST PROJECTRECONFIGUREWIZARD
	menucommand CDATA #REQUIRED
	wizardID IDREF #REQUIRED
	iconindex CDATA #IMPLIED
	backupWizardElementID CDATA #IMPLIED
>
<!ELEMENT QUICKRECONFIGURELIST (QUICKRECONFIGURE+)>
<!ELEMENT QUICKRECONFIGURE (MENUCOMMAND?, TOOLBARITEM?, WIZARDELEMENTREF)>
<!ELEMENT MENUCOMMAND (#PCDATA)>
<!ELEMENT TOOLBARITEM (#PCDATA)>
<!ATTLIST TOOLBARITEM
	kind (ToggleButton | Checkbox | PopupButton | PopupList) #REQUIRED
	iconindex CDATA #IMPLIED
>

<!ELEMENT STARTUPDIALOG (INVOKEWIZARDBUTTON|PROJECTSTATIONERYBUTTON|CHOOSEPROJECTBUTTON|LAUNCHITEMBUTTON)+>
<!ATTLIST STARTUPDIALOG
	menuCommand CDATA #IMPLIED
>
<!ELEMENT INVOKEWIZARDBUTTON EMPTY>
<!ATTLIST INVOKEWIZARDBUTTON
	buttonTitle CDATA #REQUIRED
	wizardID IDREF #REQUIRED
>
<!ELEMENT PROJECTSTATIONERYBUTTON EMPTY>
<!ATTLIST PROJECTSTATIONERYBUTTON
	buttonTitle CDATA #REQUIRED
	dialogTitle CDATA #REQUIRED
	stationeryPath CDATA #REQUIRED
>
<!ELEMENT CHOOSEPROJECTBUTTON EMPTY>
<!ATTLIST CHOOSEPROJECTBUTTON
	buttonTitle CDATA #REQUIRED
>
<!ELEMENT LAUNCHITEMBUTTON (#PCDATA)>
<!ATTLIST LAUNCHITEMBUTTON
	buttonTitle CDATA #REQUIRED
	file CDATA #REQUIRED
>
<!ELEMENT TOOLBARICONFILES EMPTY>
<!ATTLIST TOOLBARICONFILES
	normalIcons CDATA #REQUIRED
	mouseoverIcons CDATA #IMPLIED
>
<!ELEMENT WIZARDDIALOGCONFIGLIST (WIZARDDIALOGCONFIG+)>
<!ELEMENT WIZARDDIALOGCONFIG EMPTY>
<!ATTLIST WIZARDDIALOGCONFIG
	id ID #REQUIRED
	startdialog IDREF #REQUIRED
	title CDATA #REQUIRED
	skipnewdialog (No | Yes) #IMPLIED
	wizardmap (No | Yes) #IMPLIED
	wizardmapBG CDATA #IMPLIED
	allowfinish (No | Yes) #IMPLIED
>

<!ELEMENT DIALOGLIST (DIALOG+)>
<!ATTLIST DIALOGLIST
	idref IDREF #IMPLIED
>
<!ELEMENT DIALOG (TEXTLIST?, IMAGELIST?, INFOAREALIST?, DIALOGITEMLIST?, HELPBUTTONLIST?, NEXTDIALOGSLIST?)>
<!ATTLIST DIALOG
	title CDATA #IMPLIED
	optional (No | Yes) #IMPLIED
	allowHiding (Yes | No) #IMPLIED
	priority CDATA #IMPLIED
	id ID #REQUIRED
>
<!ELEMENT TEXTLIST (TEXT+)>
<!ELEMENT TEXT (CONTENT, RECTANGLE)>
<!ELEMENT CONTENT (#PCDATA)>
<!ELEMENT RECTANGLE EMPTY>
<!ATTLIST RECTANGLE
	left CDATA #REQUIRED
	top CDATA #REQUIRED
	right CDATA #REQUIRED
	bottom CDATA #REQUIRED
>
<!ELEMENT IMAGELIST (IMAGE+)>
<!ELEMENT IMAGE (FILE, RECTANGLE)>
<!ELEMENT FILE ((FIND, REPLACE)*)>
<!ATTLIST FILE
	name CDATA #REQUIRED
	group CDATA #IMPLIED
	priority CDATA #IMPLIED
	linkorder CDATA #IMPLIED
	format (Binary) #IMPLIED
	loopCounter CDATA #IMPLIED
	reconfigAction (Default|Skip|BackupAndReplace|RecreateIfMissing|ReplaceNoBackup) #IMPLIED
	isTemplateFile (No|Yes) #IMPLIED
>
<!ELEMENT FIND (#PCDATA)>
<!ELEMENT REPLACE (#PCDATA)>
<!ELEMENT INFOAREALIST (INFOAREA+)>
<!ELEMENT INFOAREA (USERLIST, POSITION?)>
<!ELEMENT USERLIST (WIZARDELEMENTREF+)>
<!ELEMENT WIZARDELEMENTREF (RECURSION?)>
<!ATTLIST WIZARDELEMENTREF
	idref IDREF #REQUIRED
>
<!ELEMENT RECURSION EMPTY>
<!ATTLIST RECURSION
	nameref CDATA #REQUIRED
	idrefs IDREFS #IMPLIED
>
<!ELEMENT POSITION (FRAME?, RECTANGLE)>
<!ELEMENT FRAME (RECTANGLE)>
<!ELEMENT DIALOGITEMLIST (DIALOGITEM+)>
<!ELEMENT DIALOGITEM (WIZARDELEMENTREF, POSITION?)>
<!ATTLIST DIALOGITEM
	description CDATA #IMPLIED
	presentationmode (Hide | ListSingleSelection | ListMultipleSelection | HierarchicalList | CheckBox | RadioBox | ComboBox | CheckListBox | EditBox | ProjectLocation | AddAdditionalFiles) #REQUIRED
	defaultstate CDATA #IMPLIED
>
<!ELEMENT HELPBUTTONLIST (HELPBUTTON+)>
<!ELEMENT HELPBUTTON (RECTANGLE)>
<!ATTLIST HELPBUTTON title CDATA #IMPLIED>
<!ATTLIST HELPBUTTON helpfile CDATA #REQUIRED>

<!ELEMENT NEXTDIALOGSLIST (NEXTDIALOGS+)>
<!ELEMENT NEXTDIALOGS (DEPENDENCY?, DIALOGREFLIST)>
<!ATTLIST NEXTDIALOGS
	mode (Replace | Add) #IMPLIED
	flow (IgnoreFollowing) #IMPLIED
	skipreconfig (No | Yes) #IMPLIED
>
<!ELEMENT DEPENDENCY (WIZARDELEMENTREF*, DEPENDENCY*)>
<!ATTLIST DEPENDENCY
	kind (AND | OR | NOT | NAND | NOR) #IMPLIED
>
<!ELEMENT DIALOGREFLIST (DIALOGREF+)>
<!ELEMENT DIALOGREF EMPTY>
<!ATTLIST DIALOGREF
	idref IDREF #REQUIRED
>
<!ELEMENT WIZARDELEMENTLIST (WIZARDELEMENT+)>
<!ELEMENT WIZARDELEMENT (DESCRIPTION?, NEXTDIALOGSLIST?, REJECTIONLIST?, RESTRICTIONLIST?, SETTINGSLIST?, EDITBOXSETTINGS?, WIZARDELEMENTLIST?)>
<!ATTLIST WIZARDELEMENT
	name CDATA #REQUIRED
	term CDATA #REQUIRED
	id ID #REQUIRED
	requireSubItems (No | Yes) #IMPLIED
>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT REJECTIONLIST (REJECTION+)>
<!ELEMENT REJECTION (DEPENDENCY?, WIZARDELEMENTREF)>
<!ELEMENT RESTRICTIONLIST (RESTRICTION+)>
<!ELEMENT RESTRICTION (DEPENDENCY?, WIZARDELEMENTREF)>
<!ELEMENT SETTINGSLIST (SETTINGS+)>
<!ELEMENT SETTINGS (TARGET?, DEPENDENCY?, FILELIST?, FOLDERLIST?, SEARCHPATHS?, OPTIONLIST?, SETTINGSLIST?, APPLYTEMPLATE?, MACROLIST?, SUBBUILDTARGETLIST?, LINKEDTARGETLIST?, WIZARDELEMENTLINKS?)>
<!ATTLIST SETTINGS
	flow (IgnoreFollowing) #IMPLIED
>
<!ELEMENT MACROLIST (MACRO+)>
<!ELEMENT MACRO (#PCDATA)>
<!ATTLIST MACRO
	name CDATA #REQUIRED
	kind (Default | Set | Append | GUID | DATE | WIZ_VERSION | PROJECT_NAME_U | PROJECT_NAME_L) #REQUIRED
	sourcefilter CDATA #IMPLIED
	destfilter CDATA #IMPLIED
	replaceInFilenames (Yes | No) #IMPLIED
	replaceInGeneratedFiles (Yes | No) #IMPLIED
	replaceInOptionsValue (Yes | No) #IMPLIED
	mustMatch (Yes | No) #IMPLIED
>
<!ELEMENT TARGET (#PCDATA)>
<!ATTLIST TARGET
	forAll (Yes | No) #IMPLIED
>
<!ELEMENT FILELIST ( COPYFOLDER*, COPYFILE*, REFERENCEFILE*, GENERATEFILE*)>
<!ELEMENT COPYFILE (SOURCE, DESTINATION)>
<!ELEMENT SOURCE (FILE)>
<!ELEMENT DESTINATION (FILE)>
<!ELEMENT REFERENCEFILE (FILE)>
<!ELEMENT GENERATEFILE (FILE, INPUT)>
<!ELEMENT INPUT (#PCDATA)>
<!ELEMENT FOLDERLIST (FOLDER+)>
<!ELEMENT FOLDER (#PCDATA)>
<!ELEMENT COPYFOLDER  (SOURCEFOLDER, DESTINATIONFOLDER)>
<!ELEMENT SOURCEFOLDER (#PCDATA)>
<!ELEMENT DESTINATIONFOLDER (#PCDATA)>
<!ELEMENT SEARCHPATHS (USERSEARCHPATHS?, SYSTEMSEARCHPATHS?)>
<!ELEMENT USERSEARCHPATHS (PATH+)>
<!ELEMENT PATH EMPTY>
<!ATTLIST PATH
	name CDATA #REQUIRED
	reconfigAction (AddIfMissing|RemoveIfUnused) #IMPLIED
	root (Project | Compiler) #IMPLIED
	recursive (Yes | No) #IMPLIED
>
<!ELEMENT SYSTEMSEARCHPATHS (PATH+)>
<!ELEMENT OPTIONLIST ((OPTION | PDATAOPTION)+)>
<!ELEMENT OPTION EMPTY>
<!ATTLIST OPTION
	pluginname CDATA #REQUIRED
	fieldname CDATA #REQUIRED
	value CDATA #REQUIRED
	insertmode (Replace | Add) #IMPLIED
	replaceMacrosInValue (Yes | No) #IMPLIED
>
<!ELEMENT PDATAOPTION EMPTY>
<!ATTLIST PDATAOPTION
	resname CDATA #REQUIRED
	value CDATA #REQUIRED
	reopen (Yes | No) #IMPLIED
>
<!ELEMENT EDITBOXSETTINGS EMPTY>
<!ATTLIST EDITBOXSETTINGS
	macro CDATA #REQUIRED
	regexp CDATA #IMPLIED
	errorMessage CDATA #IMPLIED
>
<!ELEMENT SUBBUILDTARGETLIST (SUBBUILDTARGET+)>
<!ELEMENT SUBBUILDTARGET (REFERENCE_SUBBUILDTARGET)>
<!ELEMENT REFERENCE_SUBBUILDTARGET EMPTY>
<!ATTLIST REFERENCE_SUBBUILDTARGET
	subProjectName CDATA #REQUIRED
	subBuildTargetName CDATA #REQUIRED
	linkIt (Yes | No) #REQUIRED
	buildIt (Yes | No) #REQUIRED
>

<!ELEMENT LINKEDTARGETLIST (LINKEDTARGET+)>
<!ELEMENT LINKEDTARGET EMPTY>
<!ATTLIST LINKEDTARGET
	parentTargetName CDATA #REQUIRED
	linkedTargetName CDATA #REQUIRED
	defaultTargetName CDATA #IMPLIED
>

<!ELEMENT WIZARDELEMENTLINKS (WIZARDELEMENTREF+)>

<!ELEMENT TEMPLATELIST (TEMPLATE)+>
<!ELEMENT TEMPLATE (SETTINGSLIST?)>
<!ATTLIST TEMPLATE
	id ID #REQUIRED
>
<!ELEMENT APPLYTEMPLATE (PARAMETER)*>
<!ATTLIST APPLYTEMPLATE
	idref IDREF #REQUIRED
>
<!ELEMENT PARAMETER (#PCDATA)>

=== SolaZhao/freescale/CWS12v5.2/Bin/Plugins/Support/HC12Wizard/XML/Families_HCS12VR.xml
<!DOCTYPE WIZARD SYSTEM "../wizard.dtd" [
	<!ENTITY % SHORTCUTS SYSTEM "../shortcuts.dtd">
	%SHORTCUTS;
]>
<WIZARD>
	<WIZARDELEMENTLIST>
		<WIZARDELEMENT name="" term="" id="ID_CHIP_LIST">
  		<WIZARDELEMENTLIST>
				<WIZARDELEMENT name="Family" term="HCS12" id="ID_CHIP_FAMILY_hcs12" requireSubItems="Yes">
					<DESCRIPTION>HCS12

M68HC12, HCS12 and HCS12X represent three generations of 16-bit controllers with all of them being derived from the industry standard M68HC11.</DESCRIPTION>
					<WIZARDELEMENTLIST>
						<WIZARDELEMENT name="HCS12VR" term="HCS12VR Family" id="ID_CHIP_hcs12_SUBFAMILY_VR" requireSubItems="Yes">
							<DESCRIPTION>HCS12VR Family

The S12VR family integrates an S12 microcontroller with a LIN Physical interface, a 5V regulator system to supply the microcontroller, and analog blocks to control other elements of the system which operate at vehicle battery level (e.g. relay drivers, high-side driver outputs, wake up inputs).</DESCRIPTION>
						</WIZARDELEMENT>
					</WIZARDELEMENTLIST>
  			</WIZARDELEMENT>  			
			</WIZARDELEMENTLIST>		
		</WIZARDELEMENT>    
	</WIZARDELEMENTLIST>
</WIZARD>

=== SolaZhao/freescale/CWS12v5.2/Bin/Plugins/Support/HC12Wizard/XML/OSEKAvailable.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?codewarrior wizardversion="1.0" ideversion="5.2" ?>

<!DOCTYPE WIZARD SYSTEM "../wizard.dtd">

<WIZARD>
    <DIALOGLIST idref="ID_DLG_CHIP">
         <DIALOG id="ID_DLG_CHIP">
            <DIALOGITEMLIST>
                <DIALOGITEM presentationmode="Hide">
                    <WIZARDELEMENTREF idref="ID_INST_OSEK"></WIZARDELEMENTREF>
                </DIALOGITEM>
            </DIALOGITEMLIST>
        </DIALOG>
    </DIALOGLIST>
    <WIZARDELEMENTLIST>
        <WIZARDELEMENT name="" term="" id="ID_INST_OSEK"></WIZARDELEMENT>
    </WIZARDELEMENTLIST>
</WIZARD>

=== SolaZhao/freescale/CWS12v5.2/Bin/Plugins/Support/HC12Wizard/XML/restrictions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?codewarrior wizardversion="1.0" ideversion="5.2" ?>

<!DOCTYPE WIZARD SYSTEM "../wizard.dtd">

<WIZARD>
    <WIZARDELEMENTLIST>            
      <WIZARDELEMENT name="" term="" id="ID_LANG_LIST">
         <WIZARDELEMENTLIST>            
            <WIZARDELEMENT name="" term="" id="ID_LANG_ASM"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_LANG_C"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_LANG_CPP"></WIZARDELEMENT>
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
      <WIZARDELEMENT name="" term="" id="ID_CONNECTION_LIST">
         <WIZARDELEMENTLIST>
            	<WIZARDELEMENT name="" term="" id="ID_CONN_SIM"/>
                <!--WIZARDELEMENT name="" term="" id="	"/-->
                <WIZARDELEMENT name="" term="" id="ID_CONN_PEHW_HCS12"/>
                <!--WIZARDELEMENT name="" term="" id="ID_CONN_PEHW_HCS12X"/-->
                <!--WIZARDELEMENT name="" term="" id="ID_CONN_PEHW_HCS12XE"/-->
                <!--WIZARDELEMENT name="" term="" id="ID_CONN_ST"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_ST_HCS12"/>                
                <WIZARDELEMENT name="" term="" id="ID_CONN_ST_HCS12X"/>     
                <WIZARDELEMENT name="" term="" id="ID_CONN_ST_HCS12XE"/>     
                <WIZARDELEMENT name="" term="" id="ID_CONN_HITEX"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_LAUT"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_ABAT"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_ABAT_HCS12XE"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_NL"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_SDI"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_MON"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_DB12"/>
                <WIZARDELEMENT name="" term="" id="ID_CONN_TBDML"/> 
                <WIZARDELEMENT name="" term="" id="ID_CONN_TBDML_HCS12XE"/-->      
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
      <WIZARDELEMENT name="" term="" id="ID_PRC_EXP">
         <WIZARDELEMENTLIST>
            <WIZARDELEMENT name="" term="" id="ID_PRC_EXP_NO"></WIZARDELEMENT>           
            <WIZARDELEMENT name="" term="" id="ID_PRC_EXP_INIT"></WIZARDELEMENT>           
            <WIZARDELEMENT name="" term="" id="ID_PRC_EXP_RAD"></WIZARDELEMENT>
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
      <WIZARDELEMENT name="" term="" id="ID_PC_LINT">
         <WIZARDELEMENTLIST>
            <WIZARDELEMENT name="" term="" id="ID_PC_LINT_YES"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_PC_LINT_NO"></WIZARDELEMENT>
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
      <WIZARDELEMENT name="" term="" id="ID_FL_POINT">
         <WIZARDELEMENTLIST>
            <WIZARDELEMENT name="" term="" id="ID_FL_POINT_NONE"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_FL_POINT_32"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_FL_POINT_64"></WIZARDELEMENT>
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
      <WIZARDELEMENT name="" term="" id="ID_MEM_MDL">
         <WIZARDELEMENTLIST>
            <WIZARDELEMENT name="" term="" id="ID_MEM_MDL_S"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_MEM_MDL_B"></WIZARDELEMENT>
            <WIZARDELEMENT name="" term="" id="ID_MEM_MDL_L"></WIZARDELEMENT>
         </WIZARDELEMENTLIST>
      </WIZARDELEMENT>
    </WIZARDELEMENTLIST>

   <!--REJECTIONLIST>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_DB12"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_HITEX"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_LAUT"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_NL"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_SDI"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_TBDML"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_TBDML_HCS12XE"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_MON"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ST"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ST_HCS12"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ST_HCS12X"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ST_HCS12XE"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ABAT"></WIZARDELEMENTREF>
       </REJECTION>
       <REJECTION>
           <WIZARDELEMENTREF idref="ID_CONN_ABAT_HCS12XE"></WIZARDELEMENTREF>
       </REJECTION>
   </REJECTIONLIST-->
</WIZARD>
